name: cpanel
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest codee
      uses: actions/checkout@v2
    - name: Upload ftp
      uses : SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ftp.engaz-softtest.com
        username: ${{ secrets.FTB_USERNAME }}
        password: ${{ secrets.FTB_PASSWORD }}
    - name: running command ssh
      uses: appleboy/ssh-action@master
      with:
        host: ftp.engaz-softtest.com
        username: ${{ secrets.FTB_USERNAME }}
        password: ${{ secrets.FTB_PASSWORD }}
        port: 21
        script: |
          cd flight_backend/
          npm install
