name: cpanel
'on': null
push:
  branches:
    - main
jobs: null
build:
  runs-on: ubuntu-latest
  steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: npm install
    - name: Generate build
      run: npm run build
"\_ deploy": null
"\_\_\_ name": Deploy
"\_\_\_ runs-on": ubuntu-latest
"\_\_\_ steps":
  - uses: actions/checkout@v2
  - name: Upload ftp
"\_\_\_\_\_ uses": SamKirkland/FTP-Deploy-Action@4.3.2
"\_\_\_\_\_ with": null
"\_\_\_\_\_\_\_ server": ftp.engaz-soft.com
"\_\_\_\_\_\_\_ username": cicd@engaz-soft.com
"\_\_\_\_\_\_\_ password": Kalli.linx2
