name: DMS Dashboard React (Staging)

on:
  push:
    branches:
      - master
jobs:
  # To build the project
  build-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v3
      - name: Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Installing dependencies

        run: cd flight_frontend && npm install --force --ignore-engines
        env:
          CI: false
      - name: Building project
        run: cd flight_frontend && npm run build
        env:
          NODE_OPTIONS: --max-old-space-size=32768
          CI: false

      - name: running command ssh
        uses: appleboy/ssh-action@master
        with:
         host: ftp.engaz-soft.com

         username: engafkiw
         password: Kalli.linx2
         port: 21





























